site_name: Andre Romano
site_description: Software Engineer Portfolio & Documentation
site_author: Andre Luiz Romano Madureira
site_url: https://andre-romano.github.io/

theme:
  name: material

  # Color palette toggle (Light / Dark mode)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # Features to make the site look like a modern app
  features:
    - navigation.tabs # Puts top-level sections in a top navbar
    - navigation.sections # Groups sidebar items elegantly
    - navigation.top # Adds a "back to top" button
    - search.suggest # Search bar auto-suggestions
    - content.code.copy # Adds a copy button to all code blocks!

# Add links to your GitHub and other socials in the footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andre-romano

# Your site's routing
nav:
  - Home: index.md
  - Projects: projects.md
  - About Me: about.md
